apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
  type: LoadBalancer

--- 

apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
      name: metrics
  type: LoadBalancer
